# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-projeto-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-projeto
  template:
    metadata:
      labels:
        app: meu-projeto
    spec:
      containers:
      - name: meu-projeto-container
        image: luisfelipes/meu-projeto:latest
        ports:
        - containerPort: 3000
